name: Auto Unzip Files

on:
  push:
    paths:
      - '**.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List files before unzip
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Found ZIP files:"
          find . -name "*.zip"

      - name: Extract zip files
        run: |
          for zip_file in $(find . -name "*.zip"); do
            echo "Processing: $zip_file"
            unzip -o "$zip_file"
            echo "Extraction completed for $zip_file"
          done

      - name: List files after unzip
        run: |
          echo "Directory contents after extraction:"
          ls -la

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --cached --quiet || git commit -m "📦 Extract zip contents"
          git push
